[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "S3_REGION"

[dev]
  command = "astro dev"
  port = 8890
  functions = "netlify/functions"
  targetPort = 4321